title: Bin Bi
url: "https://bin-bi.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "b.bi@alibaba-inc.com"
   link: "b.bi@alibaba-inc.com"
# - name: "Resume"
#   link: "resume.pdf"
# - name: "Contact"
#   link: "contact"
